// Mapa de nombre de selección → código ISO 3166-1 alpha-2
// Usado con la librería flag-icons (clase fi fi-XX)
export const CODIGOS = {
  "México": "mx",
  "Sudáfrica": "za",
  "Corea del Sur": "kr",
  "Chequia": "cz",
  "Canadá": "ca",
  "Bosnia y Herz.": "ba",
  "Qatar": "qa",
  "Suiza": "ch",
  "Brasil": "br",
  "Marruecos": "ma",
  "Haití": "ht",
  "Escocia": "gb-sct",
  "EE.UU.": "us",
  "Paraguay": "py",
  "Australia": "au",
  "Turquía": "tr",
  "Alemania": "de",
  "Curazao": "cw",
  "Costa de Marfil": "ci",
  "Ecuador": "ec",
  "Países Bajos": "nl",
  "Japón": "jp",
  "Suecia": "se",
  "Túnez": "tn",
  "Bélgica": "be",
  "Egipto": "eg",
  "Irán": "ir",
  "Nueva Zelanda": "nz",
  "España": "es",
  "Cabo Verde": "cv",
  "Arabia Saudita": "sa",
  "Uruguay": "uy",
  "Francia": "fr",
  "Senegal": "sn",
  "Noruega": "no",
  "Irak": "iq",
  "Argentina": "ar",
  "Argelia": "dz",
  "Austria": "at",
  "Jordania": "jo",
  "Portugal": "pt",
  "Uzbekistán": "uz",
  "Colombia": "co",
  "Congo RD": "cd",
  "Inglaterra": "gb-eng",
  "Croacia": "hr",
  "Ghana": "gh",
  "Panamá": "pa",
};

export function codigoBandera(nombre) {
  return CODIGOS[nombre] ?? null;
}